version: '3.1'
services:
  db:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: dos
        POSTGRES_PASSWORD: dos
        POSTGRES_DB: dos
    restart: always
