branch-defaults:
  default:
    environment: dos-staging
    group_suffix: null
  master:
    environment: dos-staging
environment-defaults:
  staging:
    branch: null
    repository: null
global:
  application_name: dos
  branch: null
  default_ec2_keyname: dos-backend-key
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
